config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  resources :microposts
  resources :users
  root "ideas#index"
  get 'pages/about'
  resources :ideas do
    resources :comments
  end
end

app/models/idea.rb
class Idea < ApplicationRecord
  has_many :comments
  belongs_to :user
  mount_uploader :picture, PictureUploader
  scope :search, ->(query) { where("description LIKE ? OR name LIKE ?", "%#{query}%", "%#{query}%") }
end
def self.search(search)
  if search != ""
    Idea.where(['description LIKE(?) OR name LIKE(?)', "%#{search}%", "%#{search}%"])
  else
    Idea.includes(:comments).order('created_at DESC')
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: %i[ show edit update destroy ]

  # GET /ideas or /ideas.json
  def index
    @ideas = Idea.all
    if params[:query].present? 
      @ideas = Idea.search(params[:query])
    else 
      @ideas = Idea.all
    end
  end

  # GET /ideas/1 or /ideas/1.json
  def show
    @comments = @idea.comments
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
    @users = User.all
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
    @users = User.all
  end

  # POST /ideas or /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to idea_url(@idea), notice: "Idea was successfully created." }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1 or /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to idea_url(@idea), notice: "Idea was successfully updated." }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1 or /ideas/1.json
  def destroy
    @idea.update(user_id: nil) 
    @idea.destroy!

    respond_to do |format|
      format.html { redirect_to ideas_url, notice: "Idea was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /ideas/serch
  def search
    @ideas=Idea.search(params[:keyword])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture,:user_id)
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea) do |form| %>
  <% if idea.errors.any? %>
 
    <div style="color: red">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
 <div>
  ユーザ名<br>
  <%= form.collection_select :user_id,users, :id, :name, prompt:"select a User"%>
  </div>

  <div>
    品物名
    <%= form.text_field :name %>
  </div>

  <div>
    説明
    <%= form.text_area :description %>
  </div>

  <div>
    画像
    <%= form.file_field :picture %>
  </div>

  <div>
    <%= form.submit "送信" %>
  </div>
  
<% end %>

app/views/ideas/_idea.html.erb
<div id="<%= dom_id idea %>" class="list-group-item list-group-item-action d-flex gap-3 py-3">
  <div class="d-flex flex-column gap-2 w-100">
    <h2><%= link_to User.find(idea.user_id).name, idea_path(idea) %></h2>
    <p><%= idea.description %></p>
    <small class="opacity-50 text-nowrap">Last updated <%= time_ago_in_words idea.updated_at %></small>
  </div>
  <a href="<%= idea.picture_url() %>" data-lightbox="#{idea.id}" data-title="Sample Image 3">
  <%= image_tag(idea.picture_url(:thumb), width: 150, height: 150, class: "img-thumbnail flex-shrink-0") if idea.picture? %>
</a>
  
</div>

app/views/ideas/edit.html.erb
<h1>投稿の編集</h1>

<%= render "form", idea: @idea,users: @users %>

<br>

<div>
  <%= link_to "Show this idea", @idea %> |
  <%= link_to "戻る", ideas_path %>
</div>

app/views/ideas/index.html.erb
<!--<center>
  <%= form_with url: ideas_path, method: :get, local: true do %>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "検索" %>
  <% end %>
</center>-->

<p style="color: green"><%= notice %></p>



<!--<%= link_to "新規投稿", new_idea_path, class: "btn btn-primary mb-3" %>
-->

<div class="list-group w-auto">
  <!--<a href="https://via.placeholder.com/1200x800" data-lightbox="gallery" data-title="Sample Image 3">
    <img src="https://via.placeholder.com/300" alt="Sample Image 3" class="img-thumbnail">
  </a>-->
  <% @ideas.each do |idea| %>
     <%= render idea %>
  <% end %>
</div>

<p style="text-align:right"><%= link_to image_tag("投稿.jpg", alt: "新規投稿"), new_idea_path%></p>

app/views/ideas/new.html.erb
<h1>新規投稿</h1>

<%= render "form", idea: @idea ,users: @users%>

<br>

<div>
  <%= link_to "投稿ページへ戻る", ideas_path %>
</div>

app/views/ideas/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="<%= dom_id @idea %>" class="d-flex gap-3 py-3">
  <div class="d-flex flex-column gap-2 w-100">
    <h1><%= User.find(@idea.user_id).name %></h1>
    <p><%= @idea.description %></p>
    <small class="opacity-50 text-nowrap">Last updated <%= time_ago_in_words @idea.updated_at %></small>
  </div>
  <%= image_tag(@idea.picture_url, width: 150, height: 150, class: "img-thumbnail flex-shrink-0") if @idea.picture? %>
</div>

<div class="d-flex gap-3 py-3">
  <%= link_to "投稿の編集", edit_idea_path(@idea), class: "btn btn-primary" %>
  <%= link_to "投稿ページへ戻る", ideas_path, class: "btn btn-outline-secondary" %>
  <%= button_to "投稿の破棄", @idea, method: :delete, class: "btn btn-danger", form: { data: { turbo_confirm: "よろしいですか？" } } %>
</div>

<h2>コメント</h2>
<% if @comments.any? %>
  <% @comments.each do |comment| %>
    <div>
      <p><strong><%= comment.user_name %></strong></p>
      <p><%= comment.body %></p>
      <%= button_to "Destroy this comment", idea_comment_path(@idea, comment), method: :delete, class: "btn btn-danger", form: { data: { turbo_confirm: "Are you sure?" } } %>
    </div>
  <% end %>
<% else %>
  <p>コメントがありません.</p>
<% end %>

<h2>新規コメントの追加</h2>
<%= render partial: "comments/form", locals: { idea: @idea } %>